# Config file for automatic testing at travis-ci.org

language: python

sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO="1.11"
  - DJANGO="2.0"

install: pip install tox tox-travis coverage codecov
script: tox
after_success: coverage combine && codecov
